package com.mycompany.projeto_observatorio;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class TelaInicial extends javax.swing.JFrame {
    Cidade cidade1 = new Cidade(11,"São Paulo","São Paulo");
    Cidade cidade2 = new Cidade(63,"Palmas","Tocantins");
    Cidade cidade3 = new Cidade(62,"Goiânia","Goiás");
    Associacao associacao1 = new Associacao(10,"25/01/2012");
    Associacao associacao2 = new Associacao(20,"23/02/2004");
    Observatorio observatorio1 = new Observatorio(1,cidade1);
    Observatorio observatorio2 = new Observatorio(2,cidade2);
    
    ArrayList <Visitante> visitantes = new ArrayList<>();
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        diretoNoCodigo();
    }
    
    public void diretoNoCodigo (){
        
        Visitante f = new Visitante("012345678912","Arthur","63999999",cidade1);
        visitantes.add(f);
        f = new Visitante("98765432107","Ramonez","63888888",cidade1);
        visitantes.add(f);
        f = new Visitante("65432198709","David","63777777",cidade2);
        visitantes.add(f);
        f = new Visitante("98732165403","Lucas","63666666",cidade2);
        visitantes.add(f);
        f = new VisitanteAssociado("36925814702","Reinaldo","635555555",cidade3,associacao1);
        visitantes.add(f);
        f = new VisitanteAssociado("14725836989","Francisco","63444444",cidade3,associacao2);
        visitantes.add(f);
    }
    public Visitante buscarVisitante(String cpf){
        for(Visitante visitante : visitantes){
            if(visitante.getCpf().equalsIgnoreCase(cpf)){
                return visitante;
        }
    }
        return null;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InserirVisitante = new javax.swing.JButton();
        cbxTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InserirVisitante.setText("Inserir visitante");
        InserirVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirVisitanteActionPerformed(evt);
            }
        });

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visitante", "Visitante associado" }));
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(InserirVisitante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InserirVisitante)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        
    }//GEN-LAST:event_cbxTipoActionPerformed

    private void InserirVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirVisitanteActionPerformed
        String cpf = JOptionPane.showInputDialog("Digite o cpf: ");
        if(buscarVisitante(cpf) == null){
            JOptionPane.showMessageDialog(null,"CPF incorreto ou inexistente!");
            
        }

    }//GEN-LAST:event_InserirVisitanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InserirVisitante;
    private javax.swing.JComboBox<String> cbxTipo;
    // End of variables declaration//GEN-END:variables
}
